services:
  redis:
    image: redis:7.2-rc2-alpine3.18
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD --port $REDIS_PORT
    env_file:
      - ../../.env
    volumes:
      - ../../queue/data:/data
      - ../../queue/prod-conf/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          retries: 3
          timeout: 5s

networks:
  default:
    name: netrunner
