services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
        - ./proxy/data/certbot/conf:/etc/letsencrypt
        - ./proxy/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
        - proxy


networks:
  default:
    external: true
